AppBundle\Entity\Click:
    exclusion_policy: none
    properties:
        user:
            groups: ['click']
        product:
            groups: ['click']
        match:
            groups: ['click']
